from pydantic import BaseModel, HttpUrl, Field

from .enums import Sector


class Company(BaseModel):
    name: str = ...
    sector: Sector = ...
    website: HttpUrl | None = ...
    employee_count: int = ...


class PartnerCompany(Company):
    is_active: bool = ...
