from pydantic import BaseModel, computed_field
from datetime import datetime

from .people import Member, Freelancer, Researcher


class Event(...):
    name: str
    event_type: str
    registrants: ...
    location: ...
    start_time: ...
    end_time: ...

    @computed_field
    ...
